### ISSUE TITLE
Search in several modules

### ISSUE THREAD

**Issue by heatherleaf** [GrammaticalFramework/rgl-source-browser#1]
I would like to be able to search for a function (or category or part of function name or...) without specifying the module. So if I search for `AdvNP` I get a list of all modules where it's defined.

Also: I'd like to be able to search in a collection of modules (e.g., all English or Scandinavian modules)

**Comment by johnjcamilleri** [comment]
> I would like to be able to search for a function (or category or part of function name or...) without specifying the module. So if I search for `AdvNP` I get a list of all modules where it's defined.

Should be possible.

> Also: I'd like to be able to search in a collection of modules (e.g., all English or Scandinavian modules)

The UI challenge here is how to define a collection? Checkboxes beside every module? Pattern-matching in filenames?

**Comment by heatherleaf** [comment]
> The UI challenge here is how to define a collection? Checkboxes beside every module? Pattern-matching in filenames?

Two very simple suggestions: 
1. allow selection of a folder (e.g. romanian or romance or abstract)
2. allow to not select (unselect) a folder/module, and then it applies to all shown modules (perhaps filtered) -- unselection could be done by clicking a selected module

Slightly more complicated solution: Allow shift-clicking of modules / folders

**Comment by johnjcamilleri** [comment]
So I tried building a search index for every symbol in the RGL in order to be able to look up all the places it occurs. What I ended up with was a 176MB JSON file, which is far too large to load client-side. And I am not really considering building a server backend as that will make everything more complicated hosting-wise.

If one is only searching a select group of modules, or perhaps an entire language, then maybe it's fast enough to just load each tag file and search it individually, then combine the results. But I don't think it will be possible to efficiently search the entire RGL without a server backend running a database.

**Comment by heatherleaf** [comment]
Hmm... how about only being able to search for where a symbol is defined/declared? (And not wherever it is used)

Or was that what you did already?

**Comment by johnjcamilleri** [comment]
Yes that is what I tried.

One option I haven't explored is ignoring the large-scale dictionaries, since they are disproportionately large in comparison to the other RGL modules. Maybe without them the index doesn't get too big.

**Comment by johnjcamilleri** [comment]
So, if I ignore all modules with `Dict` in the name I get a search index of 5.8MB (or 4.9 if I shorten the JSON field names). This is probably manageable client-side. It will have to mean that the search cannot look into the dictionaries, but maybe that's an acceptable trade-off.

**Comment by heatherleaf** [comment]
Good idea: the dictionaries are not essential for searching, at least not for me.

Still, the index seems large to me. Is it an ordinary JS object? How about storing it as a Trie?

**Comment by johnjcamilleri** [comment]
Well 5.8MB is the size of the JSON source as plain text; example below:

```js
[
  {
    "symbol": "A",
    "hits": [
      { "type": "cat", "location": "abstract/Cat.gf:123" },
      { "type": "cat", "location": "icelandic/Miniresource.gf:9" },
      { "type": "lincat", "location": "afrikaans/CatAfr.gf:80" },
      { "type": "lincat", "location": "amharic/CatAmh.gf:9" },
      ...
    ]
  },
  ...
]
```

This needs to be downloaded by the client, but how much space it will occupy in memory is a separate question. A Trie seems optimised for fast searching, but is it necessarily more space efficient too?

**Comment by heatherleaf** [comment]
Aha, I see. Well I guess it's possible to make the JSON more compact by turning all records to tuples:
```
[ ["A", [["cat","abstract/Cat.gf:123"], ["cat","icelandic/Miniresource.gf:9"], ...]],
... ]
```
And even more compact by building a table of all files:
```
["abstract/Cat.gf", "abstract/Noun.gf", "abstract/Adjective.gf", ..., "afrikaans/CatAfr.gf", ..., "icelandic/Miniresource.gf", ...]
```
and then just using the index in this table:
```
[ ["A", [["cat",0,123], ["cat",254,9], ["lincat",17,80], ["lincat",87,9], ...]],
--                              position in table^   ^line number in source file
--              (refers to "afrikaans/CatAfr.gf")
... ]
```
and even grouping the results by type:
```
[ ["A", [["cat",[[0,123],[254,9]]], ["lincat",[[17,80],[87,9]]], ...]],
... ]

**Comment by johnjcamilleri** [comment]
Yes there's many ways to minimise it, but I think that if the server can just send the file gzipped, which is pretty standard, then none of these refactorings should be needed.

**Comment by johnjcamilleri** [comment]
Just tested. By enabling on `mod_deflate` on Apache the actual transfer size goes down from 5.8MB to 529KB. Now all I need to is write the actual code...

**Comment by johnjcamilleri** [comment]
This is implemented in the latest version (v3).

**Comment by heatherleaf** [comment]
I guess this is the "Global matches"  column? But I never get any global matches, regardless of what I search for - what am I doing wrong? I tried e.g. "DetCN" and other common functions.  

(I'm using this one: http://www.grammaticalframework.org/~john/rgl-browser/)

**Comment by johnjcamilleri** [comment]
Huh, apparently it's not working on the live version. Works for me locally:

<img width="1375" alt="Screenshot 2020-06-25 at 10 09 19" src="https://user-images.githubusercontent.com/376723/85681824-f7c94300-b6cb-11ea-9d97-e709ce70b77c.png">

(although there is also another issue with some paths being incorrect, namely `/opt:data`). Will look into this.

**Comment by johnjcamilleri** [comment]
The search works now on live, but there's still some pesky path problems.

**Comment by johnjcamilleri** [comment]
Finally fixed now.

**Comment by heatherleaf** [comment]
Great!

But it takes bandwidth to load - it used ca 16 MB until the spinning wheel disappeared. Is that how it should be?

**Comment by johnjcamilleri** [comment]
Good catch! I mistakenly deleted the `.htaccess` file which enables compression, should be fixed now.

**Comment by heatherleaf** [comment]
Wow, now it's instant! Thanks!
