### ISSUE TITLE
Search for mentions of a function (parameter)

### ISSUE THREAD

**Issue by heatherleaf** [GrammaticalFramework/rgl-source-browser#2]
I would like to be able to search for where a function (or parameter or...) is mentioned on the right-hand-side of a function. E.g., where is the parameter `NPNomPoss` used in the English modules?

Currently, when I search for NPNomPoss in the module PhraseEng (and lot of other modules), it's shown with an indirection to ResEng - but it's not mentioned or used in PhraseEng at all. I assume it's because ResEng is opened in PhraseEng, but it's not very intuitive.

**Comment by johnjcamilleri** [comment]
> I would like to be able to search for where a function (or parameter or...) is mentioned on the right-hand-side of a function. E.g., where is the parameter `NPNomPoss` used in the English modules?

Hmm, nice idea but I don't see how this would be possible without parsing every single module and scanning its AST (and building an associated search index for every single symbol). Certainly not possible with the current setup, which uses only the output of `gf --tags`.

> Currently, when I search for NPNomPoss in the module PhraseEng (and lot of other modules), it's shown with an indirection to ResEng - but it's not mentioned or used in PhraseEng at all. I assume it's because ResEng is opened in PhraseEng, but it's not very intuitive.

Yes, the browser shows you everything that is in the **scope** of the current module, regardless of whether it's in use or not. The main intended use of the tool is to help you find definitions of imported things, which can be very tedious with grep alone.
